# Use the official Python image as the base image
FROM python:3.9

# Set environment variables for Python and buffering
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Create and set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY ./run.py /app

RUN mkdir ~/.ssh/
RUN touch ~/.ssh/known_hosts
RUN ssh-keygen -f /root/.ssh/id_rsa
RUN echo "HOST *" > ~/.ssh/config
RUN echo "StrictHostKeyChecking no" >> ~/.ssh/config
RUN ssh-keyscan serveo.net >> /root/.ssh/known_hosts
FROM taichunmin/serveo:latest

RUN ssh-keygen -t rsa -f /root/.ssh/id_rsa -q -P ""
RUN echo "HostKey /root/.ssh/id_rsa" >> /etc/ssh/sshd_config
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
RUN echo "PermitEmptyPasswords yes" >> /etc/ssh/sshd_config
RUN echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config
RUN echo "UsePAM yes" >> /etc/ssh/sshd_config
RUN echo "X11Forwarding yes" >> /etc/ssh/sshd_config
RUN echo "PrintMotd no" >> /etc/ssh/sshd_config
RUN echo "AcceptEnv LANG LC_*" >> /etc/ssh/sshd_config
RUN echo "Subsystem sftp /usr/lib/openssh/sftp-server" >> /etc/ssh/sshd_config
RUN echo "AllowTcpForwarding yes" >> /etc/ssh/sshd_config
RUN echo "GatewayPorts yes" >> /etc/ssh/sshd_config
RUN echo "AllowStreamLocalForwarding yes" >> /etc/ssh/sshd_config
RUN echo "PermitTunnel yes" >> /etc/ssh/sshd_config
RUN echo "AllowAgentForwarding yes" >> /etc/ssh/sshd_config
RUN echo "AllowUsers root" >> /etc/ssh/sshd_config

RUN chmod 700 /root/.ssh
RUN touch /root/.ssh/authorized_keys
